--ozone-platform=wayland
--use-vulkan=native
--enable-dawn-backend=vulkan
--ignore-gpu-blocklist
--enable-gpu-rasterization
--enable-zero-copy
--enable-raw-draw
--enable-drdc
--disable-gpu-driver-bug-workarounds
--disable-features=UseChromeOSDirectVideoDecoder
--enable-features=WaylandWindowDecorations,UseOzonePlatform,Vulkan,SkiaGraphite,VaapiVideoEncoder,VaapiVideoDecoder,CanvasOopRasterization,VaapiIgnoreDriverChecks,OverlayScrollbar,ParallelDownloading
--enable-hardware-overlays
--enable-accelerated-video-decode
--enable-accelerated-video-encode
--enable-accelerated-mjpeg-decode
--enable-oop-rasterization
--enable-webgl-developer-extensions
--enable-accelerated-2d-canvas
--enable-direct-composition
--enable-gpu-compositing
--enable-media-router
--enable-smooth-scrolling
--disable-search-engine-collection
--extension-mime-request-handling=always-prompt-for-install
--fingerprinting-canvas-image-data-noise
--fingerprinting-canvas-measuretext-noise
--fingerprinting-client-rects-noise
--popups-to-tabs
--force-punycode-hostnames
--show-avatar-button=incognito-and-guest
--no-default-browser-check
--no-pings
