--ignore-gpu-blocklist
--enable-zero-copy
--ozone-platform-hint=auto
--ozone-platform=wayland
--enable-wayland-ime
--process-per-site
--enable-features=WebUIDarkMode,UseOzonePlatform,VaapiVideoDecodeLinuxGL,VaapiVideoDecoder,WebRTCPipeWireCapturer,WaylandWindowDecorations
